<?php

namespace Database\Seeders;
use Illuminate\Database\Seeder;
use App\Models\Question; // Make sure to use your actual model

;

class QuestionSeeder extends Seeder
{
    public function run()
    {
        // Assuming you have fields like 'course', 'question', 'type', 'difficulty', 'score'
        for ($i = 0; $i < 50; $i++) {
            Question::create([
                'course'     => 'Sample Course ' . $i,
                'question'   => 'This is a sample question ' . $i . ' generated by Faker.',
                'type'       => ['Multiple Choice', 'True / False', 'Answer the Question'][rand(0, 2)],
                'difficulty' => ['Easy', 'Intermediate', 'Advanced', 'Medium'][rand(0, 3)],
                'score'      => rand(5, 30),
            ]);
        }
    }
}

