<?php

namespace Database\Seeders;
use Illuminate\Database\Seeder;
use App\Models\Question; 
;

class QuestionSeeder extends Seeder
{
    public function run()
    {
        for ($i = 0; $i < 50; $i++) {
            Question::create([
                'course'     => 'Sample Course ' . $i,
                'question'   => 'This is a sample question ' . $i . ' generated by Faker.',
                'type'       => ['Multiple Choice', 'True / False', 'Answer the Question'][rand(0, 2)],
                'difficulty' => ['Easy', 'Intermediate', 'Advanced', 'Medium'][rand(0, 3)],
                'score'      => rand(5, 30),
                'correct_answer' => ['True', 'False', 'A', 'B', 'C', 'D', 'Python', 'Functional-requirement'][rand(0,7)],
            ]);
        }
    }
}

